"use client"

import type React from "react"

import { createContext, useContext, useState } from "react"

type Language = "en" | "fr"

type LanguageProviderProps = {
  children: React.ReactNode
}

type LanguageProviderState = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Auth
    "auth.signIn": "Sign In",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.rememberMe": "Remember me",
    "auth.forgotPassword": "Forgot password?",
    "auth.welcome": "Welcome back",
    "auth.subtitle": "Enter your credentials to access your account",
    "auth.loggingIn": "Logging in...",
    "auth.loginFailed": "Login failed.",
    "auth.notAllowed": "You are not allowed to access this page.",
    "auth.loginSuccess": "Login successful",
    "auth.loggedInSuccessfully": "Successfully logged in",
    "auth.networkError": "Network error",

    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.users": "Users",
    "nav.transactions": "Transactions",
    "nav.logout": "Logout",
    "nav.register": "Register",
    "nav.userList": "User List",
    // Added for new sidebar buttons
    "nav.country": "Country",
    "nav.countryList": "Country List",
    "nav.countryCreate": "Create Country",
    "nav.network": "Network",
    "nav.networkList": "Network List",
    "nav.networkCreate": "Create Network",
    "nav.devices": "Devices",
    "nav.devicesList": "Devices List",
    "nav.phoneNumbers": "Phone Numbers",
    "nav.smsLogs": "SMS Logs",
    "nav.fcmLogs": "FCM Logs",
    "nav.networkConfig": "Network Config",
    "nav.networkConfigList": "Network Config List",
    "nav.networkConfigCreate": "Create Network Config",
    "nav.remoteCommand": "Remote Command",
    "nav.partner": "Partners",

    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.adminDashboard": "Admin Dashboard",
    "dashboard.liveOverview": "Live overview of your platform",
    "dashboard.activeUsers": "Active Users",
    "dashboard.activeTasks": "Active Tasks",
    "dashboard.pendingCodes": "Pending Codes",
    "dashboard.async": "Async",
    "dashboard.logging": "Logging",
    "dashboard.enabled": "Enabled",
    "dashboard.disabled": "Disabled",
    "dashboard.email": "Email",
    "dashboard.sms": "SMS",
    "dashboard.userTaskActivity": "User & Task Activity",
    "dashboard.liveActivityFeed": "Live Activity Feed",
    "dashboard.users": "Users",
    "dashboard.tasks": "Tasks",
    "dashboard.failedToLoadStats": "Failed to load dashboard stats",
    "dashboard.totalUsers": "Total Users",
    "dashboard.totalTransactions": "Total Transactions",
    "dashboard.recentActivity": "Recent User Activity",
    "dashboard.userGrowth": "User Growth",
    "dashboard.taskStats": "Task Stats",
    "dashboard.scheduledTasks": "Scheduled Tasks",
    "dashboard.reservedTasks": "Reserved Tasks",
    "dashboard.userStats": "User Stats",
    "dashboard.pendingUsers": "Pending Users",
    "dashboard.verifiedUsers": "Verified Users",
    "dashboard.usersRegisteredToday": "Users Registered Today",
    "dashboard.usersRegisteredWeek": "Users Registered This Week",
    "dashboard.codeStats": "Code Stats",
    "dashboard.pendingPasswordReset": "Pending Password Reset",
    "dashboard.pendingEmailVerification": "Pending Email Verification",
    "dashboard.pendingPhoneVerification": "Pending Phone Verification",
    "dashboard.notificationInfo": "Notification Info",
    "dashboard.emailService": "Email Service",
    "dashboard.smsService": "SMS Service",
    "dashboard.asyncEnabled": "Async Enabled",
    "dashboard.loggingEnabled": "Logging Enabled",
    "dashboard.timestamp": "Timestamp",
    "dashboard.authError": "Authentication Error",
    "dashboard.showOnlyActiveUsers": "Show only active users",
    "dashboard.success": "Success",
    "dashboard.statsLoadedSuccessfully": "Stats loaded successfully",
    // "dashboard.failedToLoadStats": "Failed to load stats",
    // "dashboard.adminDashboard": "Admin Dashboard",
    // "dashboard.liveOverview": "Live overview",
    // "dashboard.taskStats": "Task Stats",
    // "dashboard.activeTasks": "Active tasks",
    // "dashboard.scheduledTasks": "Scheduled tasks",
    // "dashboard.reservedTasks": "Reserved tasks",
    // "dashboard.userStats": "User Stats",
    // "dashboard.totalUsers": "Total users",
    // "dashboard.pendingUsers": "Pending users",
    // "dashboard.verifiedUsers": "Verified users",
    // "dashboard.usersRegisteredToday": "Users registered today",
    // "dashboard.usersRegisteredWeek": "Users registered this week",
    // "dashboard.codeStats": "Code Stats",
    // "dashboard.pendingPasswordReset": "Pending password reset",
    // "dashboard.pendingEmailVerification": "Pending email verification",
    // "dashboard.pendingPhoneVerification": "Pending phone verification",
    // "dashboard.notificationInfo": "Notification Info",
    // "dashboard.emailService": "Email service",
    // "dashboard.smsService": "SMS service",
    // "dashboard.asyncEnabled": "Async enabled",
    // "dashboard.enabled": "Enabled",
    // "dashboard.disabled": "Disabled",
    // "dashboard.loggingEnabled": "Logging enabled",
    // "dashboard.timestamp": "Timestamp",
    "dashboard.paymentSummary": "Payment Summary",
    "dashboard.todayTransactions": "Today's Transactions",
    "dashboard.todayCompleted": "Today's Completed",
    "dashboard.todayRevenue": "Today's Revenue",
    "dashboard.todaySuccessRate": "Today's Success Rate",
    "dashboard.onlineDevices": "Online Devices",
    "dashboard.pendingTransactions": "Pending Transactions",
    "dashboard.lastUpdated": "Last Updated",
    "dashboard.noData": "No data",
    "dashboard.transactionStats": "Transaction Stats",
    // "dashboard.totalTransactions": "Total Transactions",
    "dashboard.completedTransactions": "Completed",
    "dashboard.failedTransactions": "Failed",
    "dashboard.processingTransactions": "Processing",
    "dashboard.successRate": "Success Rate",
    "dashboard.avgProcessingTime": "Avg. Processing Time",
    "dashboard.totalAmount": "Total Amount",
    "dashboard.depositsCount": "Deposits",
    "dashboard.withdrawalsCount": "Withdrawals",
    "dashboard.depositsAmount": "Deposits Amount",
    "dashboard.withdrawalsAmount": "Withdrawals Amount",
    "dashboard.systemEvents": "System Events",
    "dashboard.noEvents": "No recent events",
    "dashboard.successTransactions": "Successful Transactions",
    "dashboard.financialOverview": "Financial Overview",
    "dashboard.adminActivityChart": "Admin Activity Chart",
    "dashboard.balanceOperations": "Balance Operations",
    "dashboard.periodDays": "Period (days)",
    "dashboard.totalRefunds": "Total Refunds",
    "dashboard.totalDebits": "Total Debits",
    "dashboard.totalAdjustments": "Total Adjustments",
    // "dashboard.totalRefunds": "Total Refunds",
    "dashboard.generatedAt": "Generated at",
    "dashboard.adminActivity": "Admin Activity",
    "dashboard.totalCredits": "Total Credits",
    "dashboard.rechargeRequestsStats": "Recharge Requests Stats",
    "dashboard.totalRechargeRequests": "Total Recharge Requests",
    "dashboard.totalRequests": "Total Requests",
    "dashboard.pendingReview": "Pending Review",
    "dashboard.totalApprovedAmount": "Total Approved Amount",
    "dashboard.currentMonth": "Current Month",
    "dashboard.approvedCount": "Approved Count",
    "dashboard.approvedAmount": "Approved Amount",
    "dashboard.approvalRate": "Approval Rate",
    "dashboard.byStatus": "By Status",
    
    // (Optional, currently commented in UI)
    // "dashboard.userTaskActivity": "User & Task Activity",
    // "dashboard.users": "Users",
    // "dashboard.tasks": "Tasks",
    // "dashboard.liveActivityFeed": "Live Activity Feed",

    // Users
    "users.title": "Users",
    "users.search": "Search users...",
    "users.name": "Name",
    "users.email": "Email",
    "users.status": "Status",
    "users.createdAt": "Created At",
    "users.active": "Active",
    "users.inactive": "Inactive",
    "users.pending": "Pending",
    "users.allStatuses": "All Statuses",
    "users.phone": "Phone",
    "users.emailVerified": "Email Verified",
    "users.phoneVerified": "Phone Verified",
    "users.lastLogin": "Last Login",
    "users.details": "Details",
    "users.isActive": "Is Active",
    "users.uid": "UID",
    "users.verifyEmail": "Verify Email",
    "users.verifyPhone": "Verify Phone",
    "users.contactMethod": "Contact Method",
    "users.viewType": "View Type",
    "users.pendingUsers": "Pending Users",
    "users.allUsers": "All Users",
    "users.showingResults": "Showing start to end of total results",
    "users.pageOf": "Page current and total",
    "users.sendCode": "Send Code",
    "users.verifyCode": "Verify Code",
    "users.resendCode": "Resend Code",
    "users.verificationCode": "Verification Code",
    "users.enterVerificationCode": "Enter verification code",
    "users.codeSent": "Code sent successfully",
    "users.verificationSuccess": "Verification successful",
    "users.enterIdentifierToSendCode": "Enter the {type} to send verification code",
    "users.enterCodeSentTo": "Enter the verification code sent to {identifier}",
    "users.enterEmail": "Enter email",
    "users.enterPhone": "Enter phone number",
    "users.sending": "Sending...",
    "users.verifying": "Verifying...",
    // Activation/Deactivation
    "users.activate": "Activate",
    "users.deactivate": "Deactivate",
    "users.activating": "Activating...",
    "users.deactivating": "Deactivating...",
    "users.activated": "User activated",
    "users.deactivated": "User deactivated",
    "users.activationFailed": "Failed to activate user",
    "users.deactivationFailed": "Failed to deactivate user",
    "users.userActivatedSuccessfully": "User activated successfully",
    "users.userDeactivatedSuccessfully": "User deactivated successfully",
    // Verification toggle
    "users.unverifyEmail": "Unverify Email",
    "users.unverifyPhone": "Unverify Phone",
    "users.emailUnverifiedSuccessfully": "User email unverified successfully",
    "users.phoneUnverifiedSuccessfully": "User phone unverified successfully",
    "users.confirmVerifyEmail": "Are you sure you want to verify this user's email?",
    "users.confirmUnverifyEmail": "Are you sure you want to unverify this user's email?",
    "users.confirmVerifyPhone": "Are you sure you want to verify this user's phone?",
    "users.confirmUnverifyPhone": "Are you sure you want to unverify this user's phone?",

    "users.confirmActivateTitle": "Activate User",
    "users.confirmDeactivateTitle": "Deactivate User",
    "users.confirmActivateText": "Are you sure that you want to activate user?",
    "users.confirmDeactivateText": "Are you sure that you want to deactivate user?",
    "users.disablePartner": "Disable Partner",
    "users.confirmDisablePartner": "Are you sure you want to disable this user's partner status?",

    // Transactions
    "transactions.title": "Transactions",
    "transactions.amount": "Amount",
    "transactions.user": "User",
    "transactions.date": "Date",
    "transactions.type": "Type",
    "transactions.status": "Status",
    "transactions.deposit": "Deposit",
    "transactions.withdrawal": "Withdrawal",
    "transactions.transfer": "Transfer",
    "transactions.completed": "Completed",
    "transactions.pending": "Pending",
    "transactions.failed": "Failed",
    "transactions.sentToUser": "Sent to User",
    "transactions.actions": "Actions",
    "transactions.searchByUser": "Search by user...",
    "transactions.allStatuses": "All Statuses",
    "transactions.allTypes": "All Types",
    "transactions.noTransactionsFound": "No transactions found.",
    "transactions.edit": "Edit",
    "transactions.delete": "Delete",
    "transactions.deleteTransaction": "Delete Transaction",
    "transactions.deleteConfirmation": "Are you sure you want to delete this transaction? This action cannot be undone.",
    "transactions.cancel": "Cancel",
    "transactions.editTransaction": "Edit Transaction",
    "transactions.updateTransactionDetails": "Update the transaction details below.",
    "transactions.externalTransactionId": "External Transaction ID",
    "transactions.balanceBefore": "Balance Before",
    "transactions.balanceAfter": "Balance After",
    "transactions.fees": "Fees",
    "transactions.confirmationMessage": "Confirmation Message",
    "transactions.rawSms": "Raw SMS",
    "transactions.completedAt": "Completed At",
    "transactions.errorMessage": "Error Message",
    "transactions.saving": "Saving...",
    "transactions.saveChanges": "Save Changes",
    "transactions.failedToLoad": "Failed to load transactions",
    "transactions.failedToUpdate": "Failed to update transaction.",
    "transactions.failedToDelete": "Could not delete transaction.",
    "transactions.transactionUpdated": "Transaction updated",
    "transactions.transactionUpdatedSuccess": "The transaction was updated successfully.",
    "transactions.transactionDeleted": "Transaction deleted",
    "transactions.transactionDeletedSuccess": "The transaction was deleted successfully.",
    "transactions.deleteFailed": "Delete failed",
    "transactions.showingResults": "Showing start to end of total results",
    "transactions.pageOf": "Page current and total",
    "transactions.recipientName": "Recipient Name",
    "transactions.recipientPhone": "Recipient Phone",
    "transactions.reference": "Reference",
    "transactions.network": "Network",
    "transactions.createdAt": "Created At",
    "transactions.createTransaction": "Create Transaction",
    "transactions.chooseType": "Choose Transaction Type",
    // Transactions - Assign/Retry actions
    "transactions.assign": "Assign",
    "transactions.assignSuccess": "Assigned",
    "transactions.assignedSuccessfully": "Transaction assigned successfully.",
    "transactions.assignFailed": "Assign failed",
    "transactions.userIdMissing": "User ID not found on this transaction.",
    "transactions.retry": "Retry",
    "transactions.retryTransaction": "Retry Transaction",
    "transactions.enterRetryReason": "Provide a reason for retrying this transaction.",
    "transactions.reason": "Reason",
    "transactions.reasonPlaceholder": "Tentative retry after timeout",
    "transactions.retryQueued": "Retry queued",
    "transactions.retryRequested": "Retry request sent successfully.",
    "transactions.retryFailed": "Failed to retry transaction",
    "transactions.retryReasonRequired": "Reason is required",
    "transactions.submit": "Submit",
    "transactions.sending": "Sending...",

    // Transactions - New actions: Cancel / Mark as Success
    "transactions.cancelAction": "Cancel Transaction",
    "transactions.cancelTransaction": "Cancel Transaction",
    "transactions.enterCancelReason": "Provide a reason for cancelling this transaction.",
    "transactions.cancelQueued": "Cancel queued",
    "transactions.cancelRequested": "Cancel request sent successfully.",
    "transactions.cancelFailed": "Failed to cancel transaction",
    "transactions.cancelReasonRequired": "Reason is required",

    "transactions.markSuccess": "Mark as Success",
    "transactions.successTransaction": "Mark Transaction as Success",
    "transactions.enterSuccessReason": "Provide a reason for marking this transaction as success.",
    "transactions.successQueued": "Success queued",
    "transactions.successRequested": "Success update sent successfully.",
    "transactions.successFailed": "Failed to mark transaction as success",
    "transactions.successReasonRequired": "Reason is required",
    // Transaction Forms (Deposit/Withdraw)
    "transactions.depositTitle": "Deposit",
    "transactions.selectNetwork": "Select Network",
    "transactions.confirmAmount": "Confirm Amount",
    "transactions.confirmRecipientPhone": "Confirm Recipient Phone",
    "transactions.purpose": "Purpose",
    "transactions.createDeposit": "Create Deposit",
    "transactions.depositCreatedTitle": "Deposit created",
    "transactions.transactionCreatedDesc": "Transaction created successfully",
    "transactions.failedToLoadNetworks": "Failed to load networks",
    "transactions.failedToCreateDeposit": "Failed to create deposit",
    "transactions.amountMismatch": "Amount and Confirm Amount do not match",
    "transactions.phoneMismatch": "Phone number and Confirm Phone number do not match",
    "transactions.confirmDetailsRequired": "Please confirm the phone number and amount",
    "transactions.confirmationLabel": "I confirm the phone number and amount are correct",
    "transactions.withdrawTitle": "Withdraw",
    "transactions.createWithdrawal": "Create Withdrawal",
    "transactions.withdrawalCreatedTitle": "Withdrawal created",
    "transactions.failedToCreateWithdrawal": "Failed to create withdrawal",
    "transactions.success": "Success",
    "transactions.reviewAndConfirm": "Review and Confirm",
    "transactions.confirmDepositTitle": "Confirm Deposit",
    "transactions.confirmWithdrawalTitle": "Confirm Withdrawal",
    "transactionLogs.empty": "No transaction logs found.",
    "transactions.cancelled": "Cancelled",
    

    // Partner List
    "partners.title": "Partners",
    "partner.list": "Partner List",
    "partner.details": "Partner Details",
    "partner.failedToLoad": "Failed to load partners",
    "partner.isPartner": "Is Partner",
    "partner.confirmToggle": "Are you sure you want to change partner status?",
    "partner.toggleSuccess": "Partner status updated successfully.",
    "partner.toggleFailed": "Failed to update partner status.",
    "partners.search": "Search partners...",
    "partners.allStatuses": "All Statuses",
    "partners.uid": "UID",
    "partners.name": "Name",
    "partners.email": "Email",
    "partners.phone": "Phone",
    "partners.createdAt": "Created At",
    "partners.details": "Details",
    "partners.status": "Status",
   
    "partner.actions": "Actions",
    "partners.active": "Active",
    "partners.inactive": "Inactive",
    "partners.noPartnersFound": "No partners found.",
    "partners.pageOf": "Page current and total",
    "partners.showingResults": "Showing start to end of total results",
    // Top Up Page
    "topup.title": "Top Up",
    "topup.list": "Top Up List",
    "topup.details": "Top Up Details",
    "topup.failedToLoad": "Failed to load top ups",
    "topup.search": "Search top ups...",
    "topup.filter": "Filter by status",
    "topup.allStatuses": "All Statuses",
    "topup.pending": "Pending",
    "topup.completed": "Completed",
    "topup.approved": "Approved",
    "topup.rejected": "Rejected",
    "topup.expired": "Expired",
    "topup.reject": "Reject",
    "topup.approve": "Approve",
    "topup.rejectionReason": "Rejection Reason",
    // "topup.approvalReason": "Approval Reason",
    "topup.rejectTitle": "Reject Top Up",
    "topup.approveTitle": "Approve Top Up",
    "topup.adminNotes": "Admin Notes",
    "topup.uid": "UID",
    "topup.formattedAmount": "Formatted Amount",
    "topup.userName": "User Name",
    "topup.userEmail": "User Email",
    "topup.reference": "Reference",
    "topup.amount": "Amount",
    "topup.user": "User",
    "topup.status": "Status",
    "topup.createdAt": "Created At",
    "topup.actions": "Actions",
    
    "topup.transactionDate": "Transaction Date",
    "topup.proofImage": "Proof Image",
    "topup.viewProof": "View Image",
    "topup.proofImageAlt": "Proof",
    "topup.noProofImage": "No image",
    "topup.proofDescription": "Proof Description",
    "topup.accountTransactionReference": "Account Transaction Reference",
    "topup.canSubmitProof": "Can Submit Proof",
    "topup.canBeReviewed": "Can Be Reviewed",
    "topup.isExpired": "Expired",
    "topup.timeRemaining": "Time Remaining",
    "topup.reviewedBy": "Reviewed By",
    "topup.reviewedAt": "Reviewed At",
    "topup.processedAt": "Processed At",
    // "topup.adminNotes": "Admin Notes",
    // "topup.rejectionReason": "Rejection Reason",
    "topup.confirmReject": "Reject Top Up",
    "topup.confirmApprove": "Approve Top Up",
    "topup.expireAt": "Expire At",

    "topup.noTopupsFound": "No top ups found.",
    "topup.pageOf": "Page current and total",
    "topup.showingResults": "Showing start to end of total results",
    // Earning Management Page
    "earning.title": "Earning Management",
    
    "earning.list": "Earning List",
    "earning.details": "Earning Details",
    "earning.failedToLoad": "Failed to load earnings",
    "earning.search": "Search earnings...",
    "earning.filter": "Filter by type",
    "earning.allStatuses": "All Statuses",
    "earning.pending": "Pending",
    "earning.completed": "Completed",
    "earning.approved": "Approved",
    "earning.rejected": "Rejected",
    "earning.expired": "Expired",
    "earning.formattedAmount": "Amount",
    "earning.periodStart": "Period Start",
    "earning.periodEnd": "Period End",
    "earning.adminNotes": "Admin Notes",
    "earning.paidByName": "Paid By",
    "earning.transactionsCount": "Transactions",
    "earning.noData": "No earning commissions found.",
    "earning.detailLoaded": "Earning details loaded",
    "earning.detailLoadedSuccessfully": "Earning details loaded successfully",
    "earning.detailFailed": "Failed to load earning details",
    "earning.uid": "UID",
    "earning.userName": "Name",
    "earning.userEmail": "Email",
    "earning.status": "Status",
    "earning.reference": "Reference",
    "earning.amount": "Amount",
    "earning.user": "User",
    "earning.type": "Type",
    "earning.createdAt": "Created At",
    "earning.actions": "Actions",
    "earning.noEarningsFound": "No earnings found.",
    "earning.pageOf": "Page current and total",
    "earning.showingResults": "Showing start to end of total results",
    // User Detail Modal - is_partner toggle
    "users.isPartner": "Is Partner",
    "users.confirmTogglePartner": "Are you sure you want to change partner status?",
    "users.togglePartnerSuccess": "Partner status updated successfully.",
    "users.togglePartnerFailed": "Failed to update partner status.",
    // Registration Form - is_partner
    "register.isPartner": "Is Partner",

    // Common
    "common.previous": "Previous",
    "common.next": "Next",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.actions": "Actions",
    "common.loading": "Loading...",
    "common.yes": "Yes",
    "common.close": "Close",
    "common.cancel": "Cancel",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.all": "All",
    "common.ok": "OK",
    "common.save": "Save",
    "common.errorOccurred": "An error occurred",
    "common.retry": "Retry",
    "common.retrying": "Retrying...",
    "common.dismiss": "Dismiss",
    "common.submitting": "Submitting...",
    "common.refresh": "Refresh",

    // Registration Form
    "register.title": "Register New User",
    "register.firstName": "First Name",
    "register.lastName": "Last Name",
    "register.email": "Email",
    "register.phone": "Phone",
    "register.password": "Password",
    "register.passwordConfirm": "Confirm Password",
    "register.submit": "Register User",
    "register.success": "User registered successfully!",
    "register.failed": "Registration failed.",
    "register.passwordsNoMatch": "Passwords do not match.",
    "register.networkError": "Network error.",
    "register.registering": "Registering...",
    "register.emailOrPhone": "Email or Phone",

    // Network Config
    "networkConfig.title": "Network Configuration",
    "networkConfig.list": "Network Configuration List",
    "networkConfig.create": "Create Network Configuration",
    "networkConfig.edit": "Edit Network Configuration",
    "networkConfig.add": "Add Network Config",
    "networkConfig.networkName": "Network Name",
    "networkConfig.status": "Status",
    "networkConfig.ussdCommands": "USSD Commands",
    "networkConfig.smsKeywords": "SMS Keywords",
    "networkConfig.errorKeywords": "Error Keywords",
    "networkConfig.settings": "Settings",
    "networkConfig.actions": "Actions",
    "networkConfig.active": "Active",
    "networkConfig.inactive": "Inactive",
    "networkConfig.editButton": "Edit",
    "networkConfig.network": "Network",
    "networkConfig.selectNetwork": "Select a network",
    "networkConfig.balanceCommand": "Balance Command",
    "networkConfig.depositCommand": "Deposit Command",
    "networkConfig.withdrawalCommand": "Withdrawal Command",
    "networkConfig.balanceKeywords": "Balance Keywords (comma-separated)",
    "networkConfig.depositKeywords": "Deposit Keywords (comma-separated)",
    "networkConfig.withdrawalKeywords": "Withdrawal Keywords (comma-separated)",
    "networkConfig.errorKeywordsInput": "Error Keywords (comma-separated)",
    "networkConfig.customSettings": "Custom Settings",
    "networkConfig.timeout": "Timeout (seconds)",
    "networkConfig.maxRetries": "Max Retries",
    "networkConfig.autoConfirm": "Auto Confirm",
    "networkConfig.maxRetriesLabel": "Max Retries:",
    "networkConfig.timeoutLabel": "Timeout:",
    "networkConfig.autoConfirmLabel": "Auto Confirm:",
    "networkConfig.creating": "Creating...",
    "networkConfig.saving": "Saving...",
    "networkConfig.saveChanges": "Save Changes",
    "networkConfig.cancel": "Cancel",
    "networkConfig.failedToLoad": "Failed to load network configurations",
    "networkConfig.failedToCreate": "Failed to create network configuration",
    "networkConfig.failedToUpdate": "Failed to update network configuration",
    "networkConfig.failedToLoadNetworks": "Failed to load networks",
    "networkConfig.errorLoading": "Error Loading Network Configurations",

    // Country
    "country.title": "Country",
    "country.list": "Country List",
    "country.create": "Create Country",
    "country.edit": "Edit Country",
    "country.add": "Add Country",
    "country.name": "Name",
    "country.code": "Code",
    "country.status": "Status",
    "country.actions": "Actions",
    "country.active": "Active",
    "country.inactive": "Inactive",
    "country.editButton": "Edit",
    "country.failedToLoad": "Failed to load countries",
    "country.failedToCreate": "Failed to create country",
    "country.failedToUpdate": "Failed to update country",
    "country.creating": "Creating...",
    "country.saving": "Saving...",
    "country.loading": "Loading...",
    "country.errorLoading": "Error Loading Countries",

    // Network
    "network.title": "Network",
    "network.list": "Network List",
    "network.create": "Create Network",
    "network.edit": "Edit Network",
    "network.add": "Add Network",
    "network.name": "Name",
    "network.code": "Code",
    "network.country": "Country",
    "network.status": "Status",
    "network.actions": "Actions",
    "network.active": "Active",
    "network.inactive": "Inactive",
    "network.editButton": "Edit",
    "network.ussdBaseCode": "USSD Base Code",
    "network.selectCountry": "Select a country",
    "network.creating": "Creating...",
    "network.saving": "Saving...",
    "network.save": "Save",
    "network.cancel": "Cancel",
    "network.failedToLoad": "Failed to load networks",
    "network.failedToCreate": "Failed to create network",
    "network.failedToUpdate": "Failed to update network",
    "network.failedToLoadCountries": "Failed to load countries",
    "network.loading": "Loading...",
    "network.errorLoading": "Error Loading Networks",
    "network.sentDepositToModule": "Send deposit to module",
    "network.sentWithdrawalToModule": "Send withdrawal to module",

    // Devices
    "devices.title": "Devices",
    "devices.list": "Devices List",
    "devices.failedToLoad": "Failed to load devices",
    "devices.success": "Devices loaded successfully",
    "devices.loadedSuccessfully": "Devices loaded successfully",
    "devices.deviceId": "Device ID",
    "devices.name": "Name",
    "devices.status": "Status",
    "devices.lastSync": "Last Sync",
    "devices.actions": "Actions",
    "devices.noActionsAvailable": "No actions available",
    "devices.errorLoading": "Error Loading Devices",

    // Phone Numbers
    "phoneNumbers.title": "Phone Numbers",
    "phoneNumbers.list": "Phone Numbers List",
    "phoneNumbers.failedToLoad": "Failed to load phone numbers",
    "phoneNumbers.phoneNumber": "Phone Number",
    "phoneNumbers.network": "Network",
    "phoneNumbers.fullName": "Full Name",
    "phoneNumbers.errorLoading": "Error Loading Phone Numbers",

    // SMS Logs
    "smsLogs.title": "SMS Logs",
    "smsLogs.list": "SMS Logs List",
    "smsLogs.failedToLoad": "Failed to load SMS logs",
    "smsLogs.sender": "Sender",
    "smsLogs.content": "Content",
    "smsLogs.receivedAt": "Received At",
    "smsLogs.type": "Type",
    "smsLogs.copy": "Copy",
    "smsLogs.copied": "Copied!",
    "smsLogs.errorLoading": "Error Loading SMS Logs",
    "smsLogs.showingResults": "Showing start to end of total results",
    "smsLogs.pageOf": "Page current and total",

    // FCM Logs
    "fcmLogs.title": "FCM Logs",
    "fcmLogs.list": "FCM Logs List",
    "fcmLogs.failedToLoad": "Failed to load FCM logs",
    "fcmLogs.messageTitle": "Title",
    "fcmLogs.body": "Body",
    "fcmLogs.deviceId": "Device ID",
    "fcmLogs.createdAt": "Created At",
    "fcmLogs.copy": "Copy",
    "fcmLogs.copied": "Copied!",
    "fcmLogs.errorLoading": "Error Loading FCM Logs",
    "fcmLogs.showingResults": "Showing start to end of total results",
    "fcmLogs.pageOf": "Page current and total",

    // Transaction Logs
    "transactionLogs.title": "Transaction Logs",
    "transactionLogs.list": "Transaction Logs List",
    "transactionLogs.success": "Success",
    "transactionLogs.loadedSuccessfully": "Transaction logs loaded successfully",
    "transactionLogs.failedToLoad": "Failed to load transaction logs",
    "transactionLogs.createdAt": "Created At",
    "transactionLogs.transactionId": "Transaction",
    "transactionLogs.status": "Status",
    "transactionLogs.amount": "Amount",
    "transactionLogs.details": "Details",

    // Remote Command
    "remoteCommand.title": "Remote Command",
    "remoteCommand.create": "Create Remote Command",
    "remoteCommand.failedToCreate": "Failed to create remote command",
    "remoteCommand.command": "Command",
    "remoteCommand.deviceId": "Device ID",
    "remoteCommand.parameters": "Parameters (JSON)",
    "remoteCommand.priority": "Priority",
    "remoteCommand.sending": "Sending...",
    "remoteCommand.sendCommand": "Send Command",
    "remoteCommand.parametersMustBeValidJson": "Parameters must be valid JSON",
    "remoteCommand.commandSentSuccessfully": "Command sent successfully",
    "remoteCommand.selectDeviceId": "Select a device",

    // Common additional
    "common.no": "No",
    "common.failedToLoad": "Failed to load data",
    "common.failedToCreate": "Failed to create",
    "common.failedToUpdate": "Failed to update",
    "common.failedToDelete": "Failed to delete",
    
    // Wave Business Transaction
    "waveBusiness.title": "Wave Business Transactions",
    "waveBusiness.subtitle": "Manage and monitor Wave Business transactions",
    "waveBusiness.transactions": "transactions",
    "waveBusiness.searchPlaceholder": "Search by reference...",
    "waveBusiness.phoneFilterPlaceholder": "Filter by phone...",
    "waveBusiness.allStatuses": "All Statuses",
    "waveBusiness.pending": "Pending",
    "waveBusiness.confirmed": "Confirmed",
    "waveBusiness.expired": "Expired",
    "waveBusiness.cancelled": "Cancelled",
    "waveBusiness.includeExpired": "Include expired",
    "waveBusiness.reference": "Reference",
    "waveBusiness.amount": "Amount",
    "waveBusiness.recipientPhone": "Recipient Phone",
    "waveBusiness.status": "Status",
    "waveBusiness.createdAt": "Created At",
    "waveBusiness.expiresAt": "Expires At",
    "waveBusiness.actions": "Actions",
    "waveBusiness.details": "Details",
    "waveBusiness.loadingTransactions": "Loading transactions...",
    "waveBusiness.noTransactionsFound": "No transactions found.",
    "waveBusiness.showingResults": "Showing start to end of total results",
    "waveBusiness.pageOf": "Page current and total",
    "waveBusiness.previous": "Previous",
    "waveBusiness.next": "Next",
    "waveBusiness.transactionDetails": "Transaction Details",
    "waveBusiness.uid": "UID",
    "waveBusiness.amountAsInteger": "Amount (integer)",
    "waveBusiness.createdBy": "Created By",
    "waveBusiness.callbackUrl": "Callback URL",
    "waveBusiness.updatedAt": "Updated At",
    "waveBusiness.confirmedAt": "Confirmed At",
    "waveBusiness.notConfirmed": "Not confirmed",
    "waveBusiness.isExpired": "Expired",
    "waveBusiness.fcmNotifications": "FCM Notifications",
    "waveBusiness.notifications": "notification(s)",
    "waveBusiness.close": "Close",
    "waveBusiness.copied": "copied!",
    "waveBusiness.copyUid": "Copy UID",
    "waveBusiness.copyReference": "Copy Reference",
    
    // Sign In Form
    "signIn.secureLogin": "Secure Login",
    "signIn.accessDashboard": "Access your admin dashboard",
    "signIn.sslSecure": "Secure connection with SSL encryption",
    "signIn.copyright": "© 2024 Flashpay Module. All rights reserved.",
  },
  fr: {
    // Auth
    "auth.signIn": "Se connecter",
    "auth.email": "Email",
    "auth.password": "Mot de passe",
    "auth.rememberMe": "Se souvenir de moi",
    "auth.forgotPassword": "Mot de passe oublié?",
    "auth.welcome": "Bon retour",
    "auth.subtitle": "Entrez vos identifiants pour accéder à votre compte",
    "auth.loggingIn": "Connexion...",
    "auth.loginFailed": "Échec de la connexion.",
    "auth.notAllowed": "Vous n'êtes pas autorisé à accéder à cette page.",
    "auth.loginSuccess": "Connexion réussie",
    "auth.loggedInSuccessfully": "Connexion réussie",
    "auth.networkError": "Erreur réseau",

    // Navigation
    "nav.dashboard": "Tableau de bord",
    "nav.users": "Utilisateurs",
    "nav.transactions": "Transactions",
    "nav.logout": "Déconnexion",
    "nav.register": "Enregistrer",
    "nav.userList": "Liste des utilisateurs",
    // Added for new sidebar buttons
    "nav.country": "Pays",
    "nav.countryList": "Liste des pays",
    "nav.countryCreate": "Créer un pays",
    "nav.network": "Réseau",
    "nav.networkList": "Liste des réseaux",
    "nav.networkCreate": "Créer un réseau",
    "nav.devices": "Appareils",
    "nav.devicesList": "Liste des appareils",
    "nav.phoneNumbers": "Numéros de téléphone",
    "nav.smsLogs": "Journaux SMS",
    "nav.fcmLogs": "Journaux FCM",
    "nav.networkConfig": "Configuration réseau",
    "nav.networkConfigList": "Liste des configurations réseau",
    "nav.networkConfigCreate": "Créer une configuration réseau",
    "nav.remoteCommand": "Commande à distance",
    "nav.partner": "Partenaires",

    // Dashboard
    "dashboard.title": "Tableau de bord",
    "dashboard.adminDashboard": "Tableau de bord administrateur",
    "dashboard.liveOverview": "Aperçu en direct de votre plateforme",
    "dashboard.activeUsers": "Utilisateurs actifs",
    "dashboard.activeTasks": "Tâches actives",
    "dashboard.pendingCodes": "Codes en attente",
    "dashboard.async": "Asynchrone",
    "dashboard.logging": "Journalisation",
    "dashboard.enabled": "Activé",
    "dashboard.disabled": "Désactivé",
    "dashboard.email": "Email",
    "dashboard.sms": "SMS",
    "dashboard.userTaskActivity": "Activité utilisateur et tâches",
    "dashboard.liveActivityFeed": "Flux d'activité en direct",
    "dashboard.users": "Utilisateurs",
    "dashboard.tasks": "Tâches",
    "dashboard.failedToLoadStats": "Échec du chargement des statistiques du tableau de bord",
    "dashboard.totalUsers": "Total Utilisateurs",
    "dashboard.totalTransactions": "Total Transactions",
    "dashboard.recentActivity": "Activité Récente des Utilisateurs",
    "dashboard.userGrowth": "Croissance des Utilisateurs",
    "dashboard.taskStats": "Statistiques des tâches",
    "dashboard.scheduledTasks": "Tâches planifiées",
    "dashboard.reservedTasks": "Tâches réservées",
    "dashboard.userStats": "Statistiques des utilisateurs",
    "dashboard.pendingUsers": "Utilisateurs en attente",
    "dashboard.verifiedUsers": "Utilisateurs vérifiés",
    "dashboard.usersRegisteredToday": "Utilisateurs inscrits aujourd'hui",
    "dashboard.usersRegisteredWeek": "Utilisateurs inscrits cette semaine",
    "dashboard.codeStats": "Statistiques des codes",
    "dashboard.pendingPasswordReset": "Réinitialisation du mot de passe en attente",
    "dashboard.pendingEmailVerification": "Vérification de l'email en attente",
    "dashboard.pendingPhoneVerification": "Vérification du téléphone en attente",
    "dashboard.notificationInfo": "Infos de notification",
    "dashboard.emailService": "Service Email",
    "dashboard.smsService": "Service SMS",
    "dashboard.asyncEnabled": "Async activé",
    "dashboard.loggingEnabled": "Journalisation activée",
    "dashboard.timestamp": "Horodatage",
    "dashboard.authError": "Erreur d'authentification",
    "dashboard.showOnlyActiveUsers": "Afficher uniquement les utilisateurs actifs",
    "dashboard.success": "Succès",
    "dashboard.statsLoadedSuccessfully": "Statistiques chargées avec succès",
    "dashboard.totalCredits": "Crédits totaux",
    // "dashboard.failedToLoadStats": "Échec du chargement des statistiques",
    // "dashboard.authError": "Erreur d'authentification",
    // "dashboard.adminDashboard": "Tableau de bord Admin",
    // "dashboard.liveOverview": "Aperçu en temps réel",
    // "dashboard.showOnlyActiveUsers": "Afficher uniquement les utilisateurs actifs",
    // "dashboard.taskStats": "Statistiques des tâches",
    // "dashboard.activeTasks": "Tâches actives",
    // "dashboard.scheduledTasks": "Tâches planifiées",
    // "dashboard.reservedTasks": "Tâches réservées",
    // "dashboard.userStats": "Statistiques des utilisateurs",
    // "dashboard.totalUsers": "Utilisateurs totaux",
    // "dashboard.pendingUsers": "Utilisateurs en attente",
    // "dashboard.verifiedUsers": "Utilisateurs vérifiés",
    // "dashboard.usersRegisteredToday": "Inscriptions aujourd'hui",
    // "dashboard.usersRegisteredWeek": "Inscriptions cette semaine",
    // "dashboard.codeStats": "Statistiques des codes",
    // "dashboard.pendingPasswordReset": "Réinitialisations de mot de passe en attente",
    // "dashboard.pendingEmailVerification": "Vérifications d'e-mail en attente",
    // "dashboard.pendingPhoneVerification": "Vérifications de téléphone en attente",
    // "dashboard.notificationInfo": "Informations de notification",
    // "dashboard.emailService": "Service e-mail",
    // "dashboard.smsService": "Service SMS",
    // "dashboard.asyncEnabled": "Asynchrone activé",
    // "dashboard.enabled": "Activé",
    // "dashboard.disabled": "Désactivé",
    // "dashboard.loggingEnabled": "Journalisation activée",
    // "dashboard.timestamp": "Horodatage",
    "dashboard.paymentSummary": "Résumé des paiements",
    "dashboard.todayTransactions": "Transactions du jour",
    "dashboard.todayCompleted": "Terminées aujourd'hui",
    "dashboard.todayRevenue": "Revenu du jour",
    "dashboard.todaySuccessRate": "Taux de succès du jour",
    "dashboard.onlineDevices": "Appareils en ligne",
    "dashboard.pendingTransactions": "Transactions en attente",
    "dashboard.lastUpdated": "Dernière mise à jour",
    "dashboard.noData": "Aucune donnée",
    "dashboard.transactionStats": "Statistiques des transactions",
    // "dashboard.totalTransactions": "Transactions totales",
    "dashboard.completedTransactions": "Terminées",
    "dashboard.failedTransactions": "Échouées",
    "dashboard.processingTransactions": "En traitement",
    "dashboard.successRate": "Taux de réussite",
    "dashboard.avgProcessingTime": "Temps de traitement moyen",
    "dashboard.totalAmount": "Montant total",
    "dashboard.depositsCount": "Dépôts",
    "dashboard.withdrawalsCount": "Retraits",
    "dashboard.depositsAmount": "Montant des dépôts",
    "dashboard.withdrawalsAmount": "Montant des retraits",
    "dashboard.systemEvents": "Événements système",
    "dashboard.noEvents": "Aucun événement récent",
    "dashboard.successTransactions": "Transactions réussies",
    "dashboard.financialOverview": "Aperçu financier",
    "dashboard.adminActivityChart": "Graphique d'activité admin",
    "dashboard.balanceOperations": "Opérations de solde",
    "dashboard.periodDays": "Période (jours)",
    "dashboard.totalAdjustments": "Ajustements totaux",
    "dashboard.totalDebits": "Débits totaux",
    "dashboard.totalRefunds": "Remboursements totaux",
    "dashboard.generatedAt": "Généré le",
    "dashboard.adminActivity": "Activité Admin",
    "dashboard.rechargeRequestsStats": "Statistiques des demandes de recharge",
    "dashboard.totalRechargeRequests": "Demandes de recharge totales",
    "dashboard.approvalRate": "Taux d'approbation",
    "dashboard.approvedAmount": "Montant approuvé",
    "dashboard.approvedCount": "Nombre approuvé",
    "dashboard.totalRequests": "Total des demandes",
    "dashboard.currentMonth": "Mois en cours",
    "dashboard.totalApprovedAmount": "Montant total approuvé",
    "dashboard.pendingReview": "En attente de révision",
    "dashboard.byStatus": "Par statut",
    // "dashboard.totalRequests": "Total des demandes",
    // "dashboard.totalRechargeRequests": "Demandes de recharge totales",
    // "dashboard.rechargeRequestsStats": "Statistiques des demandes de recharge",
    // (Optionnel, actuellement commenté dans l'UI)
    // "dashboard.userTaskActivity": "Activité Utilisateurs & Tâches",
    // "dashboard.users": "Utilisateurs",
    // "dashboard.tasks": "Tâches",
    // "dashboard.liveActivityFeed": "Flux d'activité en direct",

    // Users
    "users.title": "Utilisateurs",
    "users.search": "Rechercher des utilisateurs...",
    "users.name": "Nom",
    "users.email": "Email",
    "users.status": "Statut",
    "users.createdAt": "Créé le",
    "users.active": "Actif",
    "users.inactive": "Inactif",
    "users.pending": "En attente",
    "users.allStatuses": "Tous les statuts",
    "users.phone": "Téléphone",
    "users.emailVerified": "Email vérifié",
    "users.phoneVerified": "Téléphone vérifié",
    "users.lastLogin": "Dernière connexion",
    "users.details": "Détails",
    "users.isActive": "Est actif",
    "users.uid": "UID",
    "users.verifyEmail": "Vérifier l'email",
    "users.verifyPhone": "Vérifier le téléphone",
    "users.contactMethod": "Méthode de contact",
    "users.viewType": "Type de vue",
    "users.pendingUsers": "Utilisateurs en attente",
    "users.allUsers": "Tous les utilisateurs",
    "users.showingResults": "Affichage du début à la fin des résultats totaux",
    "users.pageOf": "Page actuelle du total",
    "users.sendCode": "Envoyer le code",
    "users.verifyCode": "Vérifier le code",
    "users.resendCode": "Renvoyer le code",
    "users.verificationCode": "Code de vérification",
    "users.enterVerificationCode": "Entrez le code de vérification",
    "users.codeSent": "Code envoyé avec succès",
    "users.verificationSuccess": "Vérification réussie",
    "users.enterIdentifierToSendCode": "Entrez le {type} pour envoyer le code de vérification",
    "users.enterCodeSentTo": "Entrez le code de vérification envoyé à {identifier}",
    "users.enterEmail": "Entrez l'email",
    "users.enterPhone": "Entrez le numéro de téléphone",
    "users.sending": "Envoi...",
    "users.verifying": "Vérification...",
    

    // Activation/Deactivation
    "users.activate": "Activer",
    "users.deactivate": "Désactiver",
    "users.activating": "Activation en cours...",
    "users.deactivating": "Désactivation en cours...",
    "users.activated": "Utilisateur activé",
    "users.deactivated": "Utilisateur désactivé",
    "users.activationFailed": "Échec de l'activation de l'utilisateur",
    "users.deactivationFailed": "Échec de la désactivation de l'utilisateur",
    "users.userActivatedSuccessfully": "Utilisateur activé avec succès",
    "users.userDeactivatedSuccessfully": "Utilisateur désactivé avec succès",
    // Verification toggle
    "users.unverifyEmail": "Annuler la vérification de l'email",
    "users.unverifyPhone": "Annuler la vérification du téléphone",
    "users.emailUnverifiedSuccessfully": "Email de l'utilisateur non vérifié avec succès",
    "users.phoneUnverifiedSuccessfully": "Téléphone de l'utilisateur non vérifié avec succès",
    "users.confirmVerifyEmail": "Êtes-vous sûr de vouloir vérifier l'email de cet utilisateur ?",
    "users.confirmUnverifyEmail": "Êtes-vous sûr de vouloir annuler la vérification de l'email de cet utilisateur ?",
    "users.confirmVerifyPhone": "Êtes-vous sûr de vouloir vérifier le téléphone de cet utilisateur ?",
    "users.confirmUnverifyPhone": "Êtes-vous sûr de vouloir annuler la vérification du téléphone de cet utilisateur ?",
    "users.confirmActivateTitle": "Activer l'utilisateur",
    "users.confirmDeactivateTitle": "Désactiver l'utilisateur",
    "users.confirmActivateText": "Êtes-vous sûr de vouloir activer l'utilisateur ?",
    "users.confirmDeactivateText": "Êtes-vous sûr de vouloir désactiver l'utilisateur ?",
    "users.disablePartner": "Désactiver le partenaire",
    "users.confirmDisablePartner": "Êtes-vous sûr de vouloir désactiver le statut de partenaire de cet utilisateur ?",

    // Transactions
    "transactions.title": "Transactions",
    "transactions.amount": "Montant",
    "transactions.user": "Utilisateur",
    "transactions.date": "Date",
    "transactions.type": "Type",
    "transactions.status": "Statut",
    "transactions.deposit": "Dépôt",
    "transactions.withdrawal": "Retrait",
    "transactions.transfer": "Transfert",
    "transactions.completed": "Terminé",
    "transactions.pending": "En attente",
    "transactions.failed": "Échoué",
    "transactions.sentToUser": "Envoyé à l'utilisateur",
    "transactions.actions": "Actions",
    "transactions.searchByUser": "Rechercher par utilisateur...",
    "transactions.allStatuses": "Tous les statuts",
    "transactions.allTypes": "Tous les types",
    "transactions.noTransactionsFound": "Aucune transaction trouvée.",
    "transactions.edit": "Modifier",
    "transactions.delete": "Supprimer",
    "transactions.deleteTransaction": "Supprimer la transaction",
    "transactions.deleteConfirmation": "Êtes-vous sûr de vouloir supprimer cette transaction ? Cette action ne peut pas être annulée.",
    "transactions.cancel": "Annuler",
    "transactions.editTransaction": "Modifier la transaction",
    "transactions.updateTransactionDetails": "Mettez à jour les détails de la transaction ci-dessous.",
    "transactions.externalTransactionId": "ID de transaction externe",
    "transactions.balanceBefore": "Solde avant",
    "transactions.balanceAfter": "Solde après",
    "transactions.fees": "Frais",
    "transactions.confirmationMessage": "Message de confirmation",
    "transactions.rawSms": "SMS brut",
    "transactions.completedAt": "Terminé à",
    "transactions.errorMessage": "Message d'erreur",
    "transactions.saving": "Sauvegarde...",
    "transactions.saveChanges": "Sauvegarder les modifications",
    "transactions.failedToLoad": "Échec du chargement des transactions",
    "transactions.failedToUpdate": "Échec de la mise à jour de la transaction.",
    "transactions.failedToDelete": "Impossible de supprimer la transaction.",
    "transactions.transactionUpdated": "Transaction mise à jour",
    "transactions.transactionUpdatedSuccess": "La transaction a été mise à jour avec succès.",
    "transactions.transactionDeleted": "Transaction supprimée",
    "transactions.transactionDeletedSuccess": "La transaction a été supprimée avec succès.",
    "transactions.deleteFailed": "Échec de la suppression",
    "transactions.showingResults": "Affichage du début à la fin des résultats totaux",
    "transactions.pageOf": "Page actuelle du total",
    "transactions.recipientName": "Nom du destinataire",
    "transactions.recipientPhone": "Téléphone du destinataire",
    "transactions.reference": "Référence",
    "transactions.network": "Réseau",
    "transactions.createdAt": "Créé le",
    "transactions.createTransaction": "Créer une transaction",
    "transactions.chooseType": "Choisir le type de transaction",
    // Transactions - Assign/Retry actions
    "transactions.assign": "Attribuer",
    "transactions.assignSuccess": "Attribué",
    "transactions.assignedSuccessfully": "Transaction attribuée avec succès.",
    "transactions.assignFailed": "Échec de l'attribution",
    "transactions.userIdMissing": "ID utilisateur introuvable pour cette transaction.",
    "transactions.retry": "Relancer",
    "transactions.retryTransaction": "Relancer la transaction",
    "transactions.enterRetryReason": "Fournissez une raison pour relancer cette transaction.",
    "transactions.reason": "Raison",
    "transactions.reasonPlaceholder": "Tentative de relance après timeout",
    "transactions.retryQueued": "Relance demandée",
    "transactions.retryRequested": "Demande de relance envoyée avec succès.",
    "transactions.retryFailed": "Échec de la relance de la transaction",
    "transactions.retryReasonRequired": "La raison est requise",
    "transactions.submit": "Soumettre",
    "transactions.sending": "Envoi...",

    // Transactions - New actions: Cancel / Mark as Success
    "transactions.cancelAction": "Annuler la transaction",
    "transactions.cancelTransaction": "Annuler la transaction",
    "transactions.enterCancelReason": "Fournissez une raison pour annuler cette transaction.",
    "transactions.cancelQueued": "Annulation en file d'attente",
    "transactions.cancelRequested": "Demande d'annulation envoyée avec succès.",
    "transactions.cancelFailed": "Échec de l'annulation de la transaction",
    "transactions.cancelReasonRequired": "La raison est requise",

    "transactions.markSuccess": "Marquer comme succès",
    "transactions.successTransaction": "Marquer la transaction comme succès",
    "transactions.enterSuccessReason": "Fournissez une raison pour marquer cette transaction comme succès.",
    "transactions.successQueued": "Marquage en succès en file d'attente",
    "transactions.successRequested": "Mise à jour de succès envoyée avec succès.",
    "transactions.successFailed": "Échec du marquage de la transaction comme succès",
    "transactions.successReasonRequired": "La raison est requise",
    // Transaction Forms (Deposit/Withdraw)
    "transactions.depositTitle": "Dépôt",
    "transactions.selectNetwork": "Sélectionner un réseau",
    "transactions.confirmAmount": "Confirmer le montant",
    "transactions.confirmRecipientPhone": "Confirmer le téléphone du destinataire",
    "transactions.purpose": "Objet",
    "transactions.createDeposit": "Créer un dépôt",
    "transactions.depositCreatedTitle": "Dépôt créé",
    "transactions.transactionCreatedDesc": "Transaction créée avec succès",
    "transactions.failedToLoadNetworks": "Échec du chargement des réseaux",
    "transactions.failedToCreateDeposit": "Échec de la création du dépôt",
    "transactions.amountMismatch": "Le montant et la confirmation du montant ne correspondent pas",
    "transactions.phoneMismatch": "Le numéro de téléphone et sa confirmation ne correspondent pas",
    "transactions.confirmDetailsRequired": "Veuillez confirmer le numéro de téléphone et le montant",
    "transactions.confirmationLabel": "Je confirme que le numéro de téléphone et le montant sont corrects",
    "transactions.withdrawTitle": "Retrait",
    "transactions.createWithdrawal": "Créer un retrait",
    "transactions.withdrawalCreatedTitle": "Retrait créé",
    "transactions.failedToCreateWithdrawal": "Échec de la création du retrait",
    "transactions.success": "Succès",
    "transactions.reviewAndConfirm": "Vérifier et confirmer",
    "transactions.confirmDepositTitle": "Confirmer le dépôt",
    "transactions.confirmWithdrawalTitle": "Confirmer le retrait",
    "transactionLogs.empty": "Aucun journal de transaction trouvé.",
    "transactions.cancelled": "Annulé",


    // Partner List
    "partners.title": "Partenaires",
    "partner.list": "Liste des partenaires",
    "partner.details": "Détails du partenaire",
    "partner.failedToLoad": "Échec du chargement des partenaires",
    "partner.isPartner": "Est partenaire",
    "partner.confirmToggle": "Êtes-vous sûr de vouloir changer le statut de partenaire ?",
    "partner.toggleSuccess": "Statut du partenaire mis à jour avec succès.",
    "partner.toggleFailed": "Échec de la mise à jour du statut du partenaire.",
    "partners.search": "Rechercher des partenaires...",
    "partners.allStatuses": "Tous les statuts",
    "partners.uid": "UID",
    "partners.name": "Nom",
    "partners.email": "Email",
    "partners.phone": "Téléphone",
    "partners.createdAt": "Créé le",
    "partners.details": "Détails",
    "partners.status": "Statut",
    "partner.actions": "Actions",
    "partners.active": "Actif",
    "partners.inactive": "Inactif",
    "partners.noPartnersFound": "Aucun partenaire trouvé.",
    "partners.pageOf": "Page actuelle du total",
    "partners.showingResults": "Affichage du début à la fin des résultats totaux",
    // Top Up Page
    "topup.title": "Recharge",
    "topup.list": "Liste des recharges",
    "topup.details": "Détails de la recharge",
    "topup.failedToLoad": "Échec du chargement des recharges",
    "topup.search": "Rechercher des recharges...",
    "topup.filter": "Filtrer par statut",
    "topup.allStatuses": "Tous les statuts",
    "topup.pending": "En attente",
    "topup.completed": "Terminé",
    "topup.approved": "Approuvé",
    "topup.rejected": "Rejeté",
    "topup.expired": "Expiré",
    "topup.reject": "Rejeter",
    "topup.approve": "Approuver",
    // "topup.rejectSuccess": "Recharge rejetée avec succès.",
    // "topup.approveSuccess": "Recharge approuvée avec succès.",
    // "topup.rejectFailed": "Échec du rejet de la recharge.",
    // "topup.approveFailed": "Échec de l'approbation de la recharge.",
    // "topup.rejectionReason": "Raison du rejet",
    // "topup.enterRejectionReason": "Entrez la raison du rejet",
    "topup.rejectionReason": "Raison du rejet",
    "topup.adminNotes": "Notes administrateur",
    "topup.rejectTitle": "Rejeter la recharge",
    "topup.approveTitle": "Approuver la recharge",
    "topup.expireAt": "Expirer le",


    "topup.uid": "UID",
    "topup.formattedAmount": "Montant formaté",
    "topup.userName": "Nom de l'utilisateur",
    "topup.userEmail": "Email de l'utilisateur",
    "topup.reference": "Référence",
    "topup.amount": "Montant",
    "topup.user": "Utilisateur",
    "topup.status": "Statut",
    "topup.createdAt": "Créé le",
    "topup.actions": "Actions",
    
    "topup.transactionDate": "Date de transaction",
    "topup.proofImage": "Image de preuve",
    "topup.viewProof": "Voir l'image",
    "topup.proofImageAlt": "Preuve",
    "topup.noProofImage": "Aucune image",
    "topup.proofDescription": "Description de la preuve",
    "topup.accountTransactionReference": "Référence de transaction du compte",
    "topup.canSubmitProof": "Peut soumettre une preuve",
    "topup.canBeReviewed": "Peut être vérifié",
    "topup.isExpired": "Expiré",
    "topup.timeRemaining": "Temps restant",
    "topup.reviewedBy": "Vérifié par",
    "topup.reviewedAt": "Vérifié le",
    "topup.processedAt": "Traité le",
    "topup.confirmReject": "Rejeter la recharge",
    "topup.confirmApprove": "Approuver la recharge",
    // "topup.adminNotes": "Notes administrateur",
    // "topup.rejectionReason": "Raison du rejet",
    "topup.noTopupsFound": "Aucune recharge trouvée.",
    "topup.pageOf": "Page actuelle du total",
    "topup.showingResults": "Affichage du début à la fin des résultats totaux",
    // Earning Management Page
    "earning.title": "Liste des Commissions",
    "earning.list": "Liste des gains",
    "earning.details": "Détails du gain",
    "earning.failedToLoad": "Échec du chargement des gains",
    "earning.search": "Rechercher des gains...",
    "earning.allStatuses": "Tous les statuts",
    "earning.pending": "En attente",
    "earning.completed": "Terminé",
    "earning.approved": "Approuvé",
    "earning.rejected": "Rejeté",
    "earning.expired": "Expiré",
    "earning.formattedAmount": "Montant",
    "earning.periodStart": "Début de la période",
    "earning.periodEnd": "Fin de la période",
    "earning.adminNotes": "Notes administrateur",
    "earning.paidByName": "Payé par",
    "earning.transactionsCount": "Transactions",
    "earning.noData": "Aucune commission de gain trouvée.",
    "earning.detailLoaded": "Détails du gain chargés",
    "earning.detailLoadedSuccessfully": "Détails du gain chargés avec succès",
    "earning.detailFailed": "Échec du chargement des détails du gain",
    "earning.uid": "UID",
    "earning.userName": "Nom de l'utilisateur",
    "earning.userEmail": "Email de l'utilisateur",
    "earning.status": "Statut",
    "earning.reference": "Référence",
    "earning.filter": "Filtrer par type",
    "earning.amount": "Montant",
    "earning.user": "Utilisateur",
    "earning.type": "Type",
    "earning.createdAt": "Créé le",
    "earning.actions": "Actions",
    "earning.noEarningsFound": "Aucun gain trouvé.",
    "earning.pageOf": "Page actuelle du total",
    "earning.showingResults": "Affichage du début à la fin des résultats totaux",
    // User Detail Modal - is_partner toggle
    "users.isPartner": "Est partenaire",
    "users.confirmTogglePartner": "Êtes-vous sûr de vouloir changer le statut de partenaire ?",
    "users.togglePartnerSuccess": "Statut du partenaire mis à jour avec succès.",
    "users.togglePartnerFailed": "Échec de la mise à jour du statut du partenaire.",
    // Registration Form - is_partner
    "register.isPartner": "Est partenaire",

    // Common
    "common.previous": "Précédent",
    "common.next": "Suivant",
    "common.search": "Rechercher",
    "common.filter": "Filtrer",
    "common.sort": "Trier",
    "common.actions": "Actions",
    "common.loading": "Chargement...",
    "common.yes": "Oui",
    "common.close": "Fermer",
    "common.cancel": "Annuler",
    "common.active": "Actif",
    "common.inactive": "Inactif",
    "common.all": "Tous",
    "common.ok": "OK",
    "common.save": "Enregistrer",
    "common.errorOccurred": "Une erreur s'est produite",
    "common.retry": "Réessayer",
    "common.retrying": "Nouvelle tentative...",
    "common.dismiss": "Fermer",
    "common.submitting": "Envoi...",
    "common.refresh": "Rafraîchir",

    // Registration Form
    "register.title": "Enregistrer un nouvel utilisateur",
    "register.firstName": "Prénom",
    "register.lastName": "Nom de famille",
    "register.email": "Email",
    "register.phone": "Téléphone",
    "register.password": "Mot de passe",
    "register.passwordConfirm": "Confirmer le mot de passe",
    "register.submit": "Enregistrer l'utilisateur",
    "register.success": "Utilisateur enregistré avec succès !",
    "register.failed": "Échec de l'enregistrement.",
    "register.passwordsNoMatch": "Les mots de passe ne correspondent pas.",
    "register.networkError": "Erreur réseau.",
    "register.registering": "Enregistrement...",
    "register.emailOrPhone": "Email ou téléphone",

    // Network Config
    "networkConfig.title": "Configuration réseau",
    "networkConfig.list": "Liste des configurations réseau",
    "networkConfig.create": "Créer une configuration réseau",
    "networkConfig.edit": "Modifier la configuration réseau",
    "networkConfig.add": "Ajouter une configuration réseau",
    "networkConfig.networkName": "Nom du réseau",
    "networkConfig.status": "Statut",
    "networkConfig.ussdCommands": "Commandes USSD",
    "networkConfig.smsKeywords": "Mots-clés SMS",
    "networkConfig.errorKeywords": "Mots-clés d'erreur",
    "networkConfig.settings": "Paramètres",
    "networkConfig.actions": "Actions",
    "networkConfig.active": "Actif",
    "networkConfig.inactive": "Inactif",
    "networkConfig.editButton": "Modifier",
    "networkConfig.network": "Réseau",
    "networkConfig.selectNetwork": "Sélectionner un réseau",
    "networkConfig.balanceCommand": "Commande de solde",
    "networkConfig.depositCommand": "Commande de dépôt",
    "networkConfig.withdrawalCommand": "Commande de retrait",
    "networkConfig.balanceKeywords": "Mots-clés de solde (séparés par des virgules)",
    "networkConfig.depositKeywords": "Mots-clés de dépôt (séparés par des virgules)",
    "networkConfig.withdrawalKeywords": "Mots-clés de retrait (séparés par des virgules)",
    "networkConfig.errorKeywordsInput": "Mots-clés d'erreur (séparés par des virgules)",
    "networkConfig.customSettings": "Paramètres personnalisés",
    "networkConfig.timeout": "Délai d'attente (secondes)",
    "networkConfig.maxRetries": "Nombre maximum de tentatives",
    "networkConfig.autoConfirm": "Confirmation automatique",
    "networkConfig.maxRetriesLabel": "Nombre max de tentatives :",
    "networkConfig.timeoutLabel": "Délai d'attente :",
    "networkConfig.autoConfirmLabel": "Confirmation auto :",
    "networkConfig.creating": "Création...",
    "networkConfig.saving": "Sauvegarde...",
    "networkConfig.saveChanges": "Sauvegarder les modifications",
    "networkConfig.cancel": "Annuler",
    "networkConfig.failedToLoad": "Échec du chargement des configurations réseau",
    "networkConfig.failedToCreate": "Échec de la création de la configuration réseau",
    "networkConfig.failedToUpdate": "Échec de la mise à jour de la configuration réseau",
    "networkConfig.failedToLoadNetworks": "Échec du chargement des réseaux",
    "networkConfig.errorLoading": "Erreur lors du chargement des configurations réseau",

    // Country
    "country.title": "Pays",
    "country.list": "Liste des pays",
    "country.create": "Créer un pays",
    "country.edit": "Modifier le pays",
    "country.add": "Ajouter un pays",
    "country.name": "Nom",
    "country.code": "Code",
    "country.status": "Statut",
    "country.actions": "Actions",
    "country.active": "Actif",
    "country.inactive": "Inactif",
    "country.editButton": "Modifier",
    "country.failedToLoad": "Échec du chargement des pays",
    "country.failedToCreate": "Échec de la création du pays",
    "country.failedToUpdate": "Échec de la mise à jour du pays",
    "country.creating": "Création...",
    "country.saving": "Enregistrement...",
    "country.loading": "Chargement...",
    "country.errorLoading": "Erreur lors du chargement des pays",

    // Network
    "network.title": "Réseau",
    "network.list": "Liste des réseaux",
    "network.create": "Créer un réseau",
    "network.edit": "Modifier le réseau",
    "network.add": "Ajouter un réseau",
    "network.name": "Nom",
    "network.code": "Code",
    "network.country": "Pays",
    "network.status": "Statut",
    "network.actions": "Actions",
    "network.active": "Actif",
    "network.inactive": "Inactif",
    "network.editButton": "Modifier",
    "network.ussdBaseCode": "Code de base USSD",
    "network.selectCountry": "Sélectionner un pays",
    "network.creating": "Création...",
    "network.saving": "Sauvegarde...",
    "network.save": "Sauvegarder",
    "network.cancel": "Annuler",
    "network.failedToLoad": "Échec du chargement des réseaux",
    "network.failedToCreate": "Échec de la création du réseau",
    "network.failedToUpdate": "Échec de la mise à jour du réseau",
    "network.failedToLoadCountries": "Échec du chargement des pays",
    "network.loading": "Chargement...",
    "network.errorLoading": "Erreur lors du chargement des réseaux",
    "network.sentDepositToModule": "Envoyer dépôt au module",
    "network.sentWithdrawalToModule": "Envoyer retrait au module",

    // Devices
    "devices.title": "Appareils",
    "devices.list": "Liste des appareils",
    "devices.failedToLoad": "Échec du chargement des appareils",
    "devices.success": "Appareils chargés avec succès",
    "devices.loadedSuccessfully": "Appareils chargés avec succès",
    "devices.deviceId": "ID de l'appareil",
    "devices.name": "Nom",
    "devices.status": "Statut",
    "devices.lastSync": "Dernière synchronisation",
    "devices.actions": "Actions",
    "devices.noActionsAvailable": "Aucune action disponible",
    "devices.errorLoading": "Erreur lors du chargement des appareils",

    // Phone Numbers
    "phoneNumbers.title": "Numéros de téléphone",
    "phoneNumbers.list": "Liste des numéros de téléphone",
    "phoneNumbers.failedToLoad": "Échec du chargement des numéros de téléphone",
    "phoneNumbers.phoneNumber": "Numéro de téléphone",
    "phoneNumbers.network": "Réseau",
    "phoneNumbers.fullName": "Nom complet",
    "phoneNumbers.errorLoading": "Erreur lors du chargement des numéros de téléphone",

    // SMS Logs
    "smsLogs.title": "Journaux SMS",
    "smsLogs.list": "Liste des journaux SMS",
    "smsLogs.failedToLoad": "Échec du chargement des journaux SMS",
    "smsLogs.sender": "Expéditeur",
    "smsLogs.content": "Contenu",
    "smsLogs.receivedAt": "Reçu le",
    "smsLogs.type": "Type",
    "smsLogs.copy": "Copier",
    "smsLogs.copied": "Copié !",
    "smsLogs.errorLoading": "Erreur lors du chargement des journaux SMS",
    "smsLogs.showingResults": "Affichage du début à la fin des résultats totaux",
    "smsLogs.pageOf": "Page actuelle du total",

    // FCM Logs
    "fcmLogs.title": "Journaux FCM",
    "fcmLogs.list": "Liste des journaux FCM",
    "fcmLogs.failedToLoad": "Échec du chargement des journaux FCM",
    "fcmLogs.messageTitle": "Titre",
    "fcmLogs.body": "Corps",
    "fcmLogs.deviceId": "ID de l'appareil",
    "fcmLogs.createdAt": "Créé le",
    "fcmLogs.copy": "Copier",
    "fcmLogs.copied": "Copié !",
    "fcmLogs.errorLoading": "Erreur lors du chargement des journaux FCM",
    "fcmLogs.showingResults": "Affichage du début à la fin des résultats totaux",
    "fcmLogs.pageOf": "Page actuelle du total",

    // Transaction Logs
    "transactionLogs.title": "Journaux de transactions",
    "transactionLogs.list": "Liste des journaux de transactions",
    "transactionLogs.success": "Succès",
    "transactionLogs.loadedSuccessfully": "Journaux de transactions chargés avec succès",
    "transactionLogs.failedToLoad": "Échec du chargement des journaux de transactions",
    "transactionLogs.createdAt": "Créé le",
    "transactionLogs.transactionId": "Transaction",
    "transactionLogs.status": "Statut",
    "transactionLogs.amount": "Montant",
    "transactionLogs.details": "Détails",

    // Remote Command
    "remoteCommand.title": "Commande à distance",
    "remoteCommand.create": "Créer une commande à distance",
    "remoteCommand.failedToCreate": "Échec de la création de la commande à distance",
    "remoteCommand.command": "Commande",
    "remoteCommand.deviceId": "ID de l'appareil",
    "remoteCommand.parameters": "Paramètres (JSON)",
    "remoteCommand.priority": "Priorité",
    "remoteCommand.sending": "Envoi...",
    "remoteCommand.sendCommand": "Envoyer la commande",
    "remoteCommand.parametersMustBeValidJson": "Les paramètres doivent être un JSON valide",
    "remoteCommand.commandSentSuccessfully": "Commande envoyée avec succès",
    "remoteCommand.selectDeviceId": "Sélectionnez un appareil",

    // Common additional
    "common.no": "Non",
    "common.failedToLoad": "Échec du chargement des données",
    "common.failedToCreate": "Échec de la création",
    "common.failedToUpdate": "Échec de la mise à jour",
    "common.failedToDelete": "Échec de la suppression",
    
    // Wave Business Transaction
    "waveBusiness.title": "Transactions Wave Business",
    "waveBusiness.subtitle": "Gérer et surveiller les transactions Wave Business",
    "waveBusiness.transactions": "transactions",
    "waveBusiness.searchPlaceholder": "Rechercher par référence...",
    "waveBusiness.phoneFilterPlaceholder": "Filtrer par téléphone...",
    "waveBusiness.allStatuses": "Tous les statuts",
    "waveBusiness.pending": "En attente",
    "waveBusiness.confirmed": "Confirmé",
    "waveBusiness.expired": "Expiré",
    "waveBusiness.cancelled": "Annulé",
    "waveBusiness.includeExpired": "Inclure les expirés",
    "waveBusiness.reference": "Référence",
    "waveBusiness.amount": "Montant",
    "waveBusiness.recipientPhone": "Téléphone destinataire",
    "waveBusiness.status": "Statut",
    "waveBusiness.createdAt": "Créé le",
    "waveBusiness.expiresAt": "Expire le",
    "waveBusiness.actions": "Actions",
    "waveBusiness.details": "Détails",
    "waveBusiness.loadingTransactions": "Chargement des transactions...",
    "waveBusiness.noTransactionsFound": "Aucune transaction trouvée.",
    "waveBusiness.showingResults": "Affichage du début à la fin des résultats totaux",
    "waveBusiness.pageOf": "Page actuelle du total",
    "waveBusiness.previous": "Précédent",
    "waveBusiness.next": "Suivant",
    "waveBusiness.transactionDetails": "Détails de la transaction",
    "waveBusiness.uid": "UID",
    "waveBusiness.amountAsInteger": "Montant (entier)",
    "waveBusiness.createdBy": "Créé par",
    "waveBusiness.callbackUrl": "URL de callback",
    "waveBusiness.updatedAt": "Mis à jour le",
    "waveBusiness.confirmedAt": "Confirmé le",
    "waveBusiness.notConfirmed": "Non confirmé",
    "waveBusiness.isExpired": "Expiré",
    "waveBusiness.fcmNotifications": "Notifications FCM",
    "waveBusiness.notifications": "notification(s)",
    "waveBusiness.close": "Fermer",
    "waveBusiness.copied": "copié !",
    "waveBusiness.copyUid": "Copier l'UID",
    "waveBusiness.copyReference": "Copier la référence",
    
    // Sign In Form
    "signIn.secureLogin": "Connexion Sécurisée",
    "signIn.accessDashboard": "Accédez à votre tableau de bord administrateur",
    "signIn.sslSecure": "Connexion sécurisée par chiffrement SSL",
    "signIn.copyright": "© 2024 Flashpay Module. Tous droits réservés.",

    // "users.phoneUnverifiedSuccessfully": "Phone unverified successfully",
    "users.partnerToggled": "Partner status updated",
    "users.partnerEnabledSuccessfully": "Partner status enabled successfully",
    "users.partnerDisabledSuccessfully": "Partner status disabled successfully",
    "users.partnerToggleFailed": "Failed to update partner status",
    "users.searchPlaceholder": "Search users...",
    "users.filterByStatus": "Filter by status",
    "users.copiedUid": "UID copied!",
    "users.copyUid": "Copy UID",

    "users.enablePartner": "Enable Partner",
  },
}

const initialState: LanguageProviderState = {
  language: "fr",
  setLanguage: () => null,
  t: () => "",
}

const LanguageProviderContext = createContext<LanguageProviderState>(initialState)

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>("fr")

  const t = (key: string, params?: Record<string, any>): string => {
    let text = translations[language][key as keyof (typeof translations)["en"]] || key
    if (params) {
      Object.entries(params).forEach(([param, value]) => {
        text = text.replace(`{${param}}`, String(value))
      })
    }
    return text
  }

  const value = {
    language,
    setLanguage,
    t,
  }

  return <LanguageProviderContext.Provider value={value}>{children}</LanguageProviderContext.Provider>
}

export const useLanguage = () => {
  const context = useContext(LanguageProviderContext)

  if (context === undefined) throw new Error("useLanguage must be used within a LanguageProvider")

  return context
}
